In [2]:
import pandas_datareader as pdr
import datetime

In [3]:
import quandl 
aapl = quandl.get("WIKI/AAPL", start_date="2006-10-01", end_date="2012-01-01")

In [4]:
aapl.head()

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2006-10-02,75.10,75.870,74.30,74.86,25451400.0,0.0,1.0,9.651397,9.750352,9.548586,9.620553,178159800.0
2006-10-03,74.45,74.950,73.19,74.07,28239600.0,0.0,1.0,9.567863,9.632120,9.405935,9.519027,197677200.0
2006-10-04,74.10,75.462,73.16,75.38,29610100.0,0.0,1.0,9.522883,9.697919,9.402080,9.687381,207270700.0
2006-10-05,74.53,76.160,74.13,74.83,24424400.0,0.0,1.0,9.578144,9.787621,9.526738,9.616698,170970800.0
2006-10-06,74.42,75.040,73.81,74.22,16677100.0,0.0,1.0,9.564007,9.643686,9.485614,9.538304,116739700.0

In [5]:
aapl.tail()

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2011-12-23,399.69,403.59,399.495,403.33,9621400.0,0.0,1.0,51.365736,51.866940,51.340676,51.833526,67349800.0
2011-12-27,403.10,409.09,403.020,406.53,9467000.0,0.0,1.0,51.803968,52.573767,51.793687,52.244771,66269000.0
2011-12-28,406.89,408.25,401.340,402.64,8166500.0,0.0,1.0,52.291036,52.465815,51.577784,51.744852,57165500.0
2011-12-29,403.40,405.65,400.510,405.12,7713500.0,0.0,1.0,51.842522,52.131679,51.471117,52.063566,53994500.0
2011-12-30,403.51,406.28,403.490,405.00,6416500.0,0.0,1.0,51.856659,52.212643,51.854089,52.048145,44915500.0

In [6]:
aapl.describe()

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
count,1323.000000,1323.000000,1323.000000,1323.000000,1.323000e+03,1323.0,1323.0,1323.000000,1323.000000,1323.000000,1323.000000,1.323000e+03
mean,202.303670,204.674047,199.552209,202.224393,2.689852e+07,0.0,1.0,25.998841,26.303468,25.645240,25.988653,1.882896e+08
std,98.862163,99.387200,98.208529,98.837774,1.467152e+07,0.0,0.0,12.705166,12.772640,12.621165,12.702032,1.027007e+08
min,73.420000,73.980000,72.600000,73.230000,5.624800e+06,0.0,1.0,9.435493,9.507461,9.330112,9.411076,3.937360e+07
25%,122.205000,124.270000,120.275000,122.020000,1.602910e+07,0.0,1.0,15.705046,15.970427,15.457014,15.681271,1.122037e+08
50%,176.260000,179.500000,173.080000,175.840000,2.328380e+07,0.0,1.0,22.651867,23.068252,22.243192,22.597891,1.629866e+08
75%,271.440000,273.927500,268.460000,270.900000,3.308900e+07,0.0,1.0,34.883823,35.203502,34.500852,34.814426,2.316230e+08
max,421.760000,426.700000,415.990000,422.240000,1.204632e+08,0.0,1.0,54.202038,54.836897,53.460513,54.263725,8.432424e+08

In [7]:
import pandas as pd
aapl.to_csv('data/aapl_ohlc.csv')
df = pd.read_csv('data/aapl_ohlc.csv', header=0, index_col='Date', parse_dates=True)

In [9]:
# Inspect the first rows of November-December 2006
print(aapl.loc[pd.Timestamp('2006-11-01'):pd.Timestamp('2006-12-31')].head())

              Open   High    Low  Close      Volume  Ex-Dividend  Split Ratio  \
Date
2006-11-01  81.100  81.38  78.36  79.16  21828300.0          0.0          1.0
2006-11-02  78.915  79.32  78.50  78.98  16624400.0          0.0          1.0
2006-11-03  79.360  79.53  77.79  78.29  15424600.0          0.0          1.0
2006-11-06  78.950  80.06  78.43  79.71  15520600.0          0.0          1.0
2006-11-07  80.450  81.00  80.13  80.51  18783300.0          0.0          1.0

            Adj. Open  Adj. High   Adj. Low  Adj. Close  Adj. Volume
Date
2006-11-01  10.422480  10.458464  10.070352   10.173163  152798100.0
2006-11-02  10.141677  10.193726  10.088344   10.150031  116370800.0
2006-11-03  10.198866  10.220713   9.997099   10.061356  107972200.0
2006-11-06  10.146175  10.288826  10.079348   10.243846  108644200.0
2006-11-07  10.338946  10.409629  10.297822   10.346657  131483100.0

In [10]:
# Inspect the first rows of 2007 
print(aapl.loc['2007'].head())

             Open   High    Low  Close       Volume  Ex-Dividend  Split Ratio  \
Date
2007-01-03  86.29  86.58  81.90  83.80   44225700.0          0.0          1.0
2007-01-04  84.05  85.95  83.82  85.66   30259300.0          0.0          1.0
2007-01-05  85.77  86.20  84.40  85.05   29812200.0          0.0          1.0
2007-01-08  85.96  86.53  85.28  85.47   28468100.0          0.0          1.0
2007-01-09  86.45  92.98  85.15  92.57  119617800.0          0.0          1.0

            Adj. Open  Adj. High   Adj. Low  Adj. Close  Adj. Volume
Date
2007-01-03  11.089468  11.126737  10.525291   10.769468  309579900.0
2007-01-04  10.801596  11.045773  10.772038   11.008504  211815100.0
2007-01-05  11.022640  11.077901  10.846576   10.930110  208685400.0
2007-01-08  11.047058  11.120311  10.959669   10.984086  199276700.0
2007-01-09  11.110030  11.949226  10.942962   11.896535  837324600.0

In [11]:
# Inspect November 2006
print(aapl.iloc[22:43])

              Open    High    Low  Close      Volume  Ex-Dividend  \
Date
2006-11-01  81.100  81.380  78.36  79.16  21828300.0          0.0
2006-11-02  78.915  79.320  78.50  78.98  16624400.0          0.0
2006-11-03  79.360  79.530  77.79  78.29  15424600.0          0.0
2006-11-06  78.950  80.060  78.43  79.71  15520600.0          0.0
2006-11-07  80.450  81.000  80.13  80.51  18783300.0          0.0
2006-11-08  80.020  82.690  79.89  82.45  24675600.0          0.0
2006-11-09  82.900  84.690  82.12  83.34  32966200.0          0.0
2006-11-10  83.550  83.600  82.50  83.12  13352300.0          0.0
2006-11-13  83.220  84.450  82.64  84.35  16095500.0          0.0
2006-11-14  84.800  85.000  83.90  85.00  21034100.0          0.0
2006-11-15  85.050  85.900  84.00  84.05  23404400.0          0.0
2006-11-16  84.870  86.300  84.62  85.61  24783600.0          0.0
2006-11-17  85.145  85.940  85.00  85.85  16658000.0          0.0
2006-11-20  85.400  87.000  85.20  86.47  20385500.0          0.0
2006-11-21  87.420  88.600  87.11  88.60  22238100.0          0.0
2006-11-22  88.990  90.750  87.85  90.31  23997900.0          0.0
2006-11-24  89.530  93.080  89.50  91.63  18524200.0          0.0
2006-11-27  92.510  93.159  89.50  89.54  38387000.0          0.0
2006-11-28  90.360  91.970  89.91  91.81  37006200.0          0.0
2006-11-29  93.000  93.150  90.25  91.80  41324400.0          0.0
2006-11-30  92.215  92.680  91.06  91.66  31088800.0          0.0

            Split Ratio  Adj. Open  Adj. High   Adj. Low  Adj. Close  \
Date
2006-11-01          1.0  10.422480  10.458464  10.070352   10.173163
2006-11-02          1.0  10.141677  10.193726  10.088344   10.150031
2006-11-03          1.0  10.198866  10.220713   9.997099   10.061356
2006-11-06          1.0  10.146175  10.288826  10.079348   10.243846
2006-11-07          1.0  10.338946  10.409629  10.297822   10.346657
2006-11-08          1.0  10.283685  10.626818  10.266978   10.595974
2006-11-09          1.0  10.653805  10.883845  10.553565   10.710352
2006-11-10          1.0  10.737339  10.743765  10.602400   10.682078
2006-11-13          1.0  10.694930  10.853002  10.620392   10.840151
2006-11-14          1.0  10.897982  10.923685  10.782319   10.923685
2006-11-15          1.0  10.930110  11.039347  10.795171   10.801596
2006-11-16          1.0  10.906978  11.090753  10.874849   11.002078
2006-11-17          1.0  10.942319  11.044488  10.923685   11.032922
2006-11-20          1.0  10.975090  11.180713  10.949387   11.112600
2006-11-21          1.0  11.234688  11.386335  11.194849   11.386335
2006-11-22          1.0  11.436455  11.662640  11.289949   11.606094
2006-11-24          1.0  11.505853  11.962077  11.501997   11.775732
2006-11-27          1.0  11.888824  11.972230  11.501997   11.507138
2006-11-28          1.0  11.612519  11.819427  11.554688   11.798865
2006-11-29          1.0  11.951796  11.971073  11.598383   11.797579
2006-11-30          1.0  11.850913  11.910672  11.702479   11.779588

            Adj. Volume
Date
2006-11-01  152798100.0
2006-11-02  116370800.0
2006-11-03  107972200.0
2006-11-06  108644200.0
2006-11-07  131483100.0
2006-11-08  172729200.0
2006-11-09  230763400.0
2006-11-10   93466100.0
2006-11-13  112668500.0
2006-11-14  147238700.0
2006-11-15  163830800.0
2006-11-16  173485200.0
2006-11-17  116606000.0
2006-11-20  142698500.0
2006-11-21  155666700.0
2006-11-22  167985300.0
2006-11-24  129669400.0
2006-11-27  268709000.0
2006-11-28  259043400.0
2006-11-29  289270800.0
2006-11-30  217621600.0

In [13]:

# Inspect the 'Open' and 'Close' values at 2006-11-01 and 2006-12-01
print(aapl.iloc[[22,43], [0, 3]])

            Open  Close
Date
2006-11-01  81.1  79.16
2006-12-01  91.8  91.32